#!/bin/bash

GAMEDIR="${WINEPREFIX}/drive_c/Westwood/RA2"

if [ ! -f $GAMEDIR/ra2.mix ]; then
    # create gamedir
    mkdir -p $GAMEDIR
    # open gamedir
#     xdg-open $GAMEDIR
fi

function install_cnc() {
    # Modify or remove this as required by your application.
  if [ -n "${INSTALL_URL_CNC}" ]; then
      INSTALL_EXE_CNC=$(basename "${INSTALL_URL_CNC//\?*/}")
    if [ ! -f "${TMPDIR}/${INSTALL_EXE_CNC}" ]; then
      # Downloads a file with progress using wget and yad
      wget "${INSTALL_URL_CNC}" -O "${TMPDIR}/${INSTALL_EXE_CNC}" 2>&1 | \
      perl -p -e '$| = 1; s/^.* +([0-9]+%) +([0-9,.]+[GMKB]) +([0-9hms,.]+).*$/\1\n# Downloading... \2 (\3)/' | \
      yad --progress --title="${INSTALL_EXE_CNC}" --width=400 --center --no-buttons --auto-close --auto-kill --on-top --no-escape
    fi
      # Installs the wine application
      env WINEARCH="${WINEARCH}" WINEPREFIX="${WINEPREFIX}" "${WINELOADER}" "${TMPDIR}/${INSTALL_EXE_CNC}" /silent
      # Removes the cached installers
      rm -v "${TMPDIR}/${INSTALL_EXE_CNC}" 2>/dev/null
      rm -v "${XDG_CACHE_HOME}/wine/${MONO_MSI}" 2>/dev/null
      rm -r "${XDG_CACHE_HOME}/winetricks" 2>/dev/null
  fi
}

  action=$(yad --width 400 --entry --title "C&C: Red Alert 2 Yuri's Revenge" \
      --center \
      --width=400 \
      --button="Install:0" --button="Exit:1" \
      --text "Note: This snap does not include the actual game so you have to buy or use your bought copy game files in order play!!

Copy the following RA2|YR game files to $GAMEDIR then press Install:

 > BINKW32.dll
 > BLOWFISH.dll
 > ra2.mix
 > ra2md.mix
 > language.mix
 > langmd.mix
      " \
      --entry "Multiplayer")
  ret=$?

  [[ $ret -eq 1 ]] && exit 0

  case $action in
      Multi*) cmd=$(install_cnc) ;;
      *) exit 1 ;;    
  esac

  eval $cmd 2>/dev/null
