#!/bin/bash

GAMEDIR="${WINEPREFIX}/drive_c/Westwood/RA2"

if [[ -f $GAMEDIR/CnCNetYRLauncher.exe ]]; then
  for i in OpenGL XNA; do
    if [[ ! -f "$GAMEDIR"/Resources/Binaries/$i/Localization.dll ]]; then
      if [[ -f "$GAMEDIR"/Resources/Binaries/Windows/Localization.dll ]]; then
          cp "$GAMEDIR"/Resources/Binaries/Windows/Localization.dll "$GAMEDIR"/Resources/Binaries/$i/
        else
          wget --no-check-certificate -q -nc "https://github.com/CnCNet/cncnet-yr-client-package/raw/master/Resources/Binaries/Windows/Localization.dll" -O "$GAMEDIR"/Resources/Binaries/$i/Localization.dll
      fi
    fi
  done
fi
