name: cncra2yr
title: C&C Red Alert 2 Yuri's Revenge (WINE)
version: '1.0'
summary: C&C Red Alert is a real-time strategy game.
description: |
 C&C: Red Alert 2 is a real-time strategy video game by Westwood Pacific, which was released for Microsoft Windows on October 23, 2000 as the follow-up to Command & Conquer: Red Alert. Red Alert 2 picks up at the conclusion of the Allied campaign of the first game. Its expansion is Command & Conquer: Yuri's Revenge.

 C&C: Red Alert 2 includes two different multi-player modes. One, LAN allows the player to play alongside friends and others without the use of an internet connection. The other, Online Play allows the player to play across the internet and against players from across the globe. LAN play allows for only Skirmish Mode that is available in single-player. Online play allows for tournaments, private games, public games, ladder ranking games and also contains a chat system. In 2005, control of online play for Red Alert 2 and a number of older C&C games was passed over from EA to XWIS, a community-run server.

grade: stable
confinement: strict
architectures:
  - build-on: amd64
base: core22
compression: lzo

plugs:
  shmem:
    interface: shared-memory
    private: true
  wine-runtime-c22:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime-core22
  wine-9-devel:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-9-devel-core22

environment:
  WINEDLLOVERRIDES: "mscoree,mshtml="  # Prevent pop-ups about Wine Mono and Wine Gecko
  WINEPREFIX: "$SNAP_USER_COMMON/.wine"
  WINEARCH: "win32"
  INSTALL_URL_CNC: "https://downloads.cncnet.org/CnCNet5_YR_Installer.exe"
  TRICKS: "win10"
  NO_AT_BRIDGE: 1
  DISABLE_WAYLAND: 1
  SOMMELIER_INSTALL_MONO: 0
  SOMMELIER_NO_THEME: 1
  SYSTEM_WGETRC: $SNAP/wine-runtime/etc/wgetrc

apps:
  cncra2yr:
    extensions: [gnome]
    command: bin/sommelier dotnet $WINEPREFIX/drive_c/Westwood/RA2/Resources/BinariesNET8/UniversalGL/clientogl.dll
    plugs:
      - audio-playback
      - home
      - network
      - network-bind
      - opengl
      - shmem

  dotnet:
    extensions: [gnome]
    command: bin/sommelier dotnet
    plugs:
      - audio-playback
      - home
      - network
      - network-bind
      - opengl
      - shmem

  syringe:
    extensions: [ gnome ]
    command: bin/sommelier syringe
    plugs:
      - audio-playback
      - home
      - network
      - network-bind
      - opengl
      - shmem

  wine:
    extensions: [gnome]
    command: bin/sommelier
    plugs:
      - home
      - network
      - shmem

  winetricks:
    extensions: [gnome]
    command: bin/sommelier winetricks
    plugs:
      - network

parts:
  cncra2yr:
    plugin: nil
    source: ./snap/local/src
    override-build: |
      craftctl default
      set -ex
      mkdir -p sommelier/hooks ; mv pre-install sommelier/hooks ; mv pre-init sommelier/hooks ; cp -R -p sommelier $CRAFT_PART_INSTALL
      # Pre download required dependencies
      YR_VERSION=$(wget -qO- https://github.com/CnCNet/cncnet-yr-client-package/releases/latest | grep -Eo "/yr-.*" | head -1 | sed 's|-| |' | cut -d'"' -f1 | awk '{print $2}')

      wget -q "https://github.com/CnCNet/cncnet-yr-client-package/releases/download/yr-${YR_VERSION}/package_$(wget -qO- https://github.com/CnCNet/cncnet-yr-client-package/releases/expanded_assets/yr-${YR_VERSION} | grep -Eo "/package_.*.tar.gz" | cut -d'_' -f2)" -P winedata

      cp -R -p winedata $CRAFT_PART_INSTALL
    stage:
      - sommelier
      - winedata
    build-packages:
      - wget

  # The sommelier script helps you snap Windows applications using Wine. It
  # initializes and configures Wine and installs the Windows application.
  sommelier:
    plugin: make
    source: https://github.com/mmtrt/sommelier-core.git
    source-branch: "yr-dotnet-core22"
    build-packages:
      - libc6-dev-i386
      - gcc-multilib
